# Generated by Django 6.0.6 on 2026-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(max_length=11)),
                ('receiver', models.TextField(max_length=11)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
