# Generated by Django 6.0.6 on 2026-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='PhoneNumber',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
